services:
  servidor_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_web_devops
    ports:
      - "8080:80"
    networks:
      - red_privada_devops
    volumes:
      - volumen_logs_web:/var/log/nginx
    depends_on:
      - base_datos_cache

  base_datos_cache:
    image: redis:alpine
    container_name: app_cache_devops
    networks:
      - red_privada_devops
    volumes:
      - volumen_datos_redis:/data

# Definición de Redes Personalizadas
networks:
  red_privada_devops:
    driver: bridge

# Definición de Volúmenes Personalizados
volumes:
  volumen_logs_web:
  volumen_datos_redis:
