name: DevOps CI-CD Pipeline

on:
  push:
    branches: [ "develop" ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 1. Pruebas Automatizadas (Validar YAML)
        run: docker-compose config || docker compose config

      - name: 2. Copiar archivos al Servidor Linux (EC2)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/proyecto_final_devops"

      - name: 3. Construccion, Despliegue y Rollback en EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install docker-compose -y
            cd /home/ubuntu/proyecto_final_devops
            chmod +x deploy.sh
            ./deploy.sh
